baseURL: 
languageCode: en-us
defaultContentLanguage: en
title: What They Forgot to Teach You
theme: cayman-hugo-theme
googleAnalytics: 
disqusShortname: 
pygmentsCodefences: yes
pygmentsStyle: pygments
taxonomies:
  tag: tags
permalinks:
  post: /:filename/
params:
  blockquote_text_color: '#819198'
  body_link_color: '#1e6bb8'
  body_text_color: '#606c71'
  border_color: '#dce6f0'
  code_background_color: '#f3f6fa'
  code_text_color: '#567482'
  dateFormat: '2006-01-02'
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cayman](https://github.com/zwbetz-gh/cayman-hugo-theme).
  header_background_color: '#159957'
  header_background_color_secondary: '#155799'
  header_heading_color: '#fff'
  hr_border_color: '#eff0f1'
  katex: yes
  large_breakpoint: 64em
  medium_breakpoint: 42em
  project_name: Cayman Hugo Theme
  project_tagline: What They Forgot to Teach You (when Using R)
  section_headings_color: '#159957'
  table_border_color: '#e9ebec'
menu:
  nav:
    - name: introduction
      url: /
      weight: 1
    - name: materials
      url: /materials/
      weight: 2
    - name: Instructors
      url: /instructors/
      weight: 3
#    - name: RSS
#      url: /index.xml
#      weight: 4
