baseurl: "https://imci-idaho.github.io/2022-03-01-WhatTheyForgot"
languageCode: "en-us"
title: "What They Forgot to Teach You About R"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
enableEmoji: true
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
#  note: "/note/:year/:month/:day/:slug/"
#  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Details
      url: "details/"
      weight: 2
    - name: Course Materials
      url: "course-materials/"
      weight: 3
    - name: Resources
      url: "resources/"
      weight: 4

params:
  description: "A workshop offerred by University of Idaho Carpentries"
  footer: "&copy; [University of Idaho](https://www.uidaho.edu) {Year} | [Github](https://github.com/imci-idaho/2022-03-01-WhatTheyForgot)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
